name: Matrix Configurations

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [hello-world, alpine]

    steps:
      - name: Docker Version
        run: docker --version

      - name: Run Image
        run: docker run ${{ matrix.image }}