name: Matrix Configurations

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        image: [hello-world, alpine]

    runs-on: ubuntu-latest

    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image
        run: docker run ${{ matrix.image }}